// Generated by IB v0.3.1 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation Camera

@end


@implementation UIView

@end


@implementation UIAlertView

@end


@implementation ClickedButton

@end


@implementation UIViewController

@end


@implementation InvalidURLError

@end


@implementation InvalidFileError

@end


@implementation BubbleWrap

@end


@implementation BubbleWrap

@end


@implementation Base

@end


@implementation FormController

@end


@implementation FormableController

@end


@implementation InvalidClassError

@end


@implementation InvalidSectionError

@end


@implementation NoRowTypeError

@end


@implementation Conditions

@end


@implementation Form

@end


@implementation Form

@end


@implementation Object

@end


@implementation NSData

@end


@implementation UIActionSheet

@end


@implementation UITextField

@end


@implementation UITextField_Delegate

@end


@implementation UITextView

@end


@implementation UITextView_Delegate

@end


@implementation UITextView

@end


@implementation Row

@end


@implementation BackRow

@end


@implementation Base

@end


@implementation ButtonRow

@end


@implementation CheckRow

@end


@implementation CurrencyRow

@end


@implementation DateRow

@end


@implementation EditRow

@end


@implementation EmailRow

@end


@implementation ImageRow

@end


@implementation NumberRow

@end


@implementation OptionsRow

@end


@implementation PhoneRow

@end


@implementation PickerRow

@end


@implementation SliderRow

@end


@implementation StaticRow

@end


@implementation StringRow

@end


@implementation SubformRow

@end


@implementation SubmitRow

@end


@implementation SwitchRow

@end


@implementation TemplateRow

@end


@implementation TextRow

@end


@implementation Section

@end


@implementation AnimationChain

@end


@implementation CLLocationCoordinate2D

@end


@implementation String

@end


@implementation SugarNotFoundException

@end


@implementation Fixnum

@end


@implementation NSArray

@end


@implementation NSCoder

@end


@implementation NSData

@end


@implementation NSDate

@end


@implementation NSIndexPath

@end


@implementation IndexPath

@end


@implementation NSIndexSet

@end


@implementation NSString

@end


@implementation NSString

@end


@implementation NSURL

@end


@implementation NSUserDefaults

@end


@implementation Object

@end


@implementation NilClass

@end


@implementation NSArray

@end


@implementation NSDictionary

@end


@implementation Numeric

@end


@implementation Symbol

@end


@implementation Symbol

@end


@implementation Numeric

@end


@implementation NSError

@end


@implementation NSLayoutConstraint

@end


@implementation NSNotification

@end


@implementation NSSet

@end


@implementation NSURL

@end


@implementation UIColor

@end


@implementation UIEvent

@end


@implementation UILabel

@end


@implementation UITextField

@end


@implementation UITouch

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation UIActionSheet

@end


@implementation UIActivityIndicatorView

@end


@implementation UIAlertView

@end


@implementation UIBarButtonItem

@end


@implementation UIButton

@end


@implementation UIColor

@end


@implementation UIControl

@end


@implementation UIImage

@end


@implementation UILabel

@end


@implementation UISegmentedControl

@end


@implementation UITextView

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation UINavigationController

@end


@implementation UITabBarController

@end


@implementation UIWebView

@end


@implementation Errbit

@end


@implementation Host

@end


@implementation HostSettingsController

@end


@implementation HostSettingsStore

@end


@implementation ProblemController

@end


@implementation ProblemsController

@end


@implementation ServersController

@end


@implementation DynamicLabel

@end

